'use client';

import { useState } from 'react';
import { CalendarDays, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Contract = { symbol:string; type:string; strike:number; bid:number; ask:number; impliedVolatility:number|null; delta:number|null; moneyness:'ITM'|'OTM'; distancePct:number };
type Chain = { symbol:string; spot:number; expiration:string; contracts:Contract[]; latencyMs:number; sourceCount:number };
const money = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const number = new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});

export default function Home(){
  const [ticker,setTicker]=useState('MU'); const [chain,setChain]=useState<Chain|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function loadChain(event:React.FormEvent){event.preventDefault();const symbol=ticker.trim().toUpperCase();setTicker(symbol);if(!/^[A-Z][A-Z.\-]{0,9}$/.test(symbol)){setError('Enter a valid ticker such as MU, AAPL, or SPY.');return}setLoading(true);setError('');try{const response=await fetch(`/api/options?symbol=${encodeURIComponent(symbol)}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'The option chain could not be loaded.');setChain(data)}catch(reason){setChain(null);setError(reason instanceof Error?reason.message:'The option chain could not be loaded.')}finally{setLoading(false)}}
  return <>
    <header className="site-header"><a className="brand" href="/">CSP Options Demo</a><nav aria-label="Primary navigation"><a href="#chain">Option chain</a><a href="/architecture">Architecture</a><a href="#about">About this demo</a></nav></header>
    <main><section className="search-section" aria-labelledby="page-title"><div><h1 id="page-title">Explore an option chain</h1><p>Enter a ticker to see five in-the-money and five out-of-the-money call contracts around the nearest expiration.</p></div><form className="ticker-form" onSubmit={loadChain}><label className="sr-only" htmlFor="ticker">Stock ticker</label><Input id="ticker" value={ticker} maxLength={10} autoComplete="off" spellCheck={false} onChange={event=>setTicker(event.target.value)}/><Button type="submit" disabled={loading}>{loading?'Loading…':'Load chain'}<ChevronRight aria-hidden="true"/></Button></form></section>
      <section id="chain" aria-live="polite" aria-busy={loading}>{error&&<p className="status-message" role="alert">{error}</p>}{chain?<><div className="market-context"><div className="symbol-block"><strong>{chain.symbol}</strong></div><div className="context-item"><span className="context-value">{money.format(chain.spot)}</span><span>Latest trade</span></div><div className="context-item context-wide"><CalendarDays aria-hidden="true"/><span className="context-value">{new Date(`${chain.expiration}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})} expiration</span></div><div className="context-item"><span className="context-value">{chain.contracts.length} contracts</span><span>{chain.latencyMs} ms · {chain.sourceCount} scanned</span></div></div><div className="table-wrap"><table><thead><tr><th>Moneyness</th><th>Contract</th><th>Type</th><th className="number">Strike</th><th className="number">Bid</th><th className="number">Ask</th><th className="number optional">IV</th><th className="number optional">Delta</th></tr></thead><tbody>{chain.contracts.map((row,index)=><tr key={row.symbol} className={index===5?'group-start':''}><td><span className={`money-tag ${row.moneyness.toLowerCase()}`}>{row.moneyness}</span> <small>{row.distancePct>0?'+':''}{row.distancePct}%</small></td><td className="contract">{row.symbol}</td><td>{row.type}</td><td className="number">{number.format(row.strike)}</td><td className="number">{number.format(row.bid)}</td><td className="number">{number.format(row.ask)}</td><td className="number optional">{row.impliedVolatility==null?'—':`${(row.impliedVolatility*100).toFixed(1)}%`}</td><td className="number optional">{row.delta==null?'—':row.delta.toFixed(3)}</td></tr>)}</tbody></table></div></>:!error&&<div className="empty-state"><div className="empty-mark" aria-hidden="true">10</div><h2>Ready for a ticker</h2><p>The demo will select one expiration and return only the ten contracts closest to the latest trade.</p></div>}</section>
      <section id="about" className="about-section"><h2>Why Alpaca is useful here</h2><p>One authenticated request provides current option snapshots with quotes, implied volatility, and Greeks. Deterministic code then applies the project rules; an AI workflow can explain or research the result without inventing the market data.</p></section></main>
    <footer>Market data via Alpaca <span>·</span> Demo only <span>·</span> No orders are submitted</footer>
  </>;
}
